function [quad,nq] = quadconn(nr,nc)
%QUADCONN Generates quadrilateral connectivity for rectangular regions.
%
%         QUAD = QUADCONN(NR,NC) Given the number of rows, NR, and
%         number of columns, NC, in the coordinate matrices generated by
%         meshgrid or ndgrid, generates the four column quadrilateral
%         connectivity matrix, QUAD.  
%
%         [QUAD,NQ] = QUADCONN(NR,NC) Returns the number of
%         quadrilateral elements, NQ.
%
%         NOTES:  None.
%
%         27-March-2014 * Mack Gardner-Morse
%

%#######################################################################
%
% Check the Inputs
%
if (nargin<1)
  error(' *** ERROR in QUADCONN:  Not enough input arguments!');
end
%
if (nargin<2)
  if isnumeric(nr)
    nr = nr(:);
    if size(nr,1)==2
      nc = nr(2);
      nr = nr(1);
    else
      error(' *** ERROR in QUADCONN:  Two numeric values are required!');
    end
  else
    error(' *** ERROR in QUADCONN:  Inputs must be numeric!');
  end
end
%
% Quadrilateral Connectivity
%
quad = (1:nr-1)';
quad = [quad quad+nr quad+nr+1 quad+1];
quad = repmat(quad,nc-1,1);
addcol = repmat(nr*(0:nc-2),(nr-1)*4,1);
addcol = reshape(addcol,4,(nc-1)*(nr-1))';
quad = quad+addcol;     % Quadrilateral connectivity matrix
%
nq = size(quad,1);
%
return